global:
  scrape_interval: 5s
  evaluation_interval: 5s
  scrape_timeout: 5s
  external_labels:
    cluster: 'surrealdb'
    monitor: "prometheus"

scrape_configs:
  - job_name: 'pd'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'pd0:2379'
      - 'pd1:2379'
      - 'pd2:2379'

  - job_name: 'tikv'
    honor_labels: true  # Do not overwrite job & instance labels.
    static_configs:
    - targets:
      - 'tikv0:20180'
      - 'tikv1:20180'
      - 'tikv2:20180'

...